version: '3.7'
services:
    app:
        container_name: bela-tagarela
        build: .
        volumes:
            - '.:/app'
            - '/app/node_modules'
        ports:
            - '3001:3001'
        environment:
            - NODE_ENV=development